export const metadata = {
    title: "Contact",
    keywords: "React.js Next.js TypeScript",
    description: "Generated by create next app",
}

export default function contact() {
    return <>Contact</>
}
