// import { Suspense } from "react"
import { CapsOn } from "./funcs/capsOn"
import { MouseUp } from "./funcs/mouseUp"
import "./globals.css"
import CartContextProvider from "./items/cart/cartContext"
import Menu from "./navigation/menu"
import NavContextProvider from "./navigation/navContext"
import Nav from "./navigation/navbar"
import UserContextProvider from "./user/userContext"

import { Montserrat } from "next/font/google"
const montserrat = Montserrat({
    weight: ["400", "700"],
    subsets: ["latin"],
    variable: "--font-montserrat",
})

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={`${montserrat.className}`}>
                {/* <Suspense fallback={<p>Loading...</p>}> */}
                <UserContextProvider>
                    <CartContextProvider>
                        <NavContextProvider>
                            <Nav />
                            <main>
                                <div>
                                    <Menu />
                                </div>
                                <div>{children}</div>
                            </main>
                            {/* <Footer/> */}
                            <CapsOn />
                            <MouseUp />
                        </NavContextProvider>
                    </CartContextProvider>
                </UserContextProvider>
                {/* </Suspense> */}
            </body>
        </html>
    )
}
