import { CapsOn } from "./funcs/capsOn"
import { MouseUp } from "./funcs/mouseUp"
import "./globals.css"
import CartContextProvider from "./items/cart/cartContext"
import Menu from "./navigation/menu"
import NavContextProvider from "./navigation/navContext"
import Nav from "./navigation/navbar"
import UserContextProvider from "./user/userContext"

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <UserContextProvider>
                    <CartContextProvider>
                        <NavContextProvider>
                            <Nav />
                            <main>
                                <div>
                                    <Menu />
                                </div>
                                <div>{children}</div>
                            </main>
                            <CapsOn />
                            <MouseUp />
                        </NavContextProvider>
                    </CartContextProvider>
                </UserContextProvider>
            </body>
        </html>
    )
}
