"use client"

import { GitHubLink } from "./home/githubLink"
import HomeMap from "./home/homeMap"
import { UserContext } from "./user/userContext"

export const metadata = {
    title: "Home",
    description: "Generated by create next app",
}

export default async function Home() {
    const { user } = UserContext()

    return (
        <>
            {user ? <h1 className="c y">Hi {user.name}!</h1> : null}
            <br />
            <GitHubLink />
            <br />
            <HomeMap />
        </>
    )
}
